format = """
[ \uf4b5 ](bg:#99a3c4 fg:#090c0c)\
[\ue0b0](bg:#7ca359 fg:#99a3c4)\
$directory\
[\ue0b0](fg:#7ca359 bg:#394260)\
$git_branch\
$git_status\
[\ue0b0](fg:#394260 bg:#212736)\
$bun\
$nodejs\
$rust\
$golang\
$php\
[\ue0b0](fg:#212736) """

right_format = """
$cmd_duration\
[\ue0b2](fg:#1d2230)\
$time\
"""

[cmd_duration]
min_time = 1000

[directory]
style = "fg:#090c0c bg:#7ca359"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#99a3c4 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#99a3c4 bg:#394260)]($style)'

[bun]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#99a3c4 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#99a3c4 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#99a3c4 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#99a3c4 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
